baseURL = ""
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"                             # en / zh-cn / ... (This field determines which i18n file to use)
title = "zeromake 的个人博客"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = false
theme = "even"
enableGitInfo = true # use git commit log to generate lastmod record # 可根据 Git 中的提交生成最近更新记录。

# Syntax highlighting by Chroma. NOTE: Don't enable `highlightInClient` and `chroma` at the same time!
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 12                                              # 首页每页显示的文章数
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: author.name ↓        # 默认为下面配置的author.name ↓

[author]                  # essential                     # 必需
  name = "zeromake<a390720046@gmail.com>"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu              # 配置目录
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "分类"
  weight = 40
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "关于"
  pre = "user"
  url = "/about/"
  identifier = "about"
  weight = 50

[permalinks]
  post = "/pages/:slug/"
  page = "/:slug/"

[params]
  version = "4.x"           # Used to give a friendly message when you have an incompatible update
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda

  since = "2016"            # Site creation time          # 站点建立时间
  # use public git repo url to link lastmod git commit, enableGitInfo should be true.
  # 指定 git 仓库地址，可以生成指向最近更新的 git commit 的链接，需要将 enableGitInfo 设置成 true.
  gitRepo = "https://github.com/zeromake/zeromake.github.io"

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = "zeromake"        # default: the title value    # 默认值: 上面设置的title值
  keywords = ["个人博客","Golang","高并发","笔记"]
  description = "zeromake 的个人博客"

  # paginate of archives, tags and categories             # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
  archivePaginate = 50

  # show 'xx Posts In Total' in archive page ?            # 是否在归档页显示文章的总数
  showArchiveCount = true

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02 15:04:05 +08:00"

  # show word count and read time ?                       # 是否显示字数统计与阅读时间
  moreMeta = true

  # Syntax highlighting by highlight.js
  highlightInClient = false

  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true                                                                            # 是否开启目录
  autoCollapseToc = true   # Auto expand and collapse toc                              # 目录自动展开/折叠
  fancybox = true           # see https://github.com/fancyapps/fancybox                 # 是否启用fancybox（图片可点击）

  # mathjax
  mathjax = false           # see https://www.mathjax.org/                              # 是否使用mathjax（数学公式）
  mathjaxEnableSingleDollar = true                                                     # 是否使用 $...$ 即可進行inline latex渲染
  mathjaxEnableAutoNumber = false                                                       # 是否使用公式自动编号
  mathjaxUseLocalFiles = false  # You should install mathjax in `your-site/static/lib/mathjax`

  # katex
  katex = true
  katexInlineSelecter = ".tex-inline"
  katexBlockSelecter = ".tex-block"

  postMetaInFooter = true   # contain author, lastMod, markdown link, license           # 包含作者，上次修改时间，markdown链接，许可信息
  linkToMarkDown = false    # Only effective when hugo will output .md files.           # 链接到markdown原始文件（仅当允许hugo生成markdown文件时有效）
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'     # e.g. '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  changyanAppid = ""        # Changyan app id             # 畅言
  changyanAppkey = ""       # Changyan app key

  livereUID = ""            # LiveRe UID                  # 来必力

  baiduPush = false        # baidu push                  # 百度
  baiduAnalytics = ""      # Baidu Analytics
  baiduVerification = ""   # Baidu Verification
  googleVerification = ""  # Google Verification         # 谷歌

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []
  customJS = []

  uglyURLs = false          # please keep same with uglyurls setting

  # Show language selector for multilingual site.
  showLanguageSelector = false

  [params.publicCDN]        # load these files from public cdn                          # 启用公共CDN，需自行定义
    enable = true
    # https://blog.skk.moe/post/public-cdn-in-diffrent-views/
    # fastly.jsdelivr.net
#     jquery = '<script src="https://fastly.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js" crossorigin="anonymous"></script>'
#     slideout = '<script src="https://fastly.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" crossorigin="anonymous"></script>'
#     fancyboxJS = '<script src="https://fastly.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js" crossorigin="anonymous"></script>'
#     fancyboxCSS = '<link rel="stylesheet" href="https://fastly.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css"crossorigin="anonymous">'
#     timeagoJS = '<script src="https://fastly.jsdelivr.net/npm/timeago.js@4.0.2/dist/timeago.min.js"crossorigin="anonymous"></script>'
    timeagoLocalesJS = ''
#     flowchartDiagramsJS = """
# <script src="https://fastly.jsdelivr.net/npm/raphael@2.3.0/raphael.min.js"crossorigin="anonymous"></script>
# <script src="https://fastly.jsdelivr.net/npm/flowchart.js@1.8.0/release/flowchart.min.js" crossorigin="anonymous"></script>"""
#     sequenceDiagramsCSS = '<link rel="stylesheet" href="https://fastly.jsdelivr.net/npm/js-sequence-diagram@2.0.1/dist/sequence-diagram-min.min.css" crossorigin="anonymous">'
#     sequenceDiagramsJS = """
# <script src="https://fastly.jsdelivr.net/npm/webfontloader@1.6.28/webfontloader.js" crossorigin="anonymous"></script>
# <script src="https://fastly.jsdelivr.net/npm/@aibee/snapsvg@0.5.5/dist/snap.svg.min.js" crossorigin="anonymous"></script>
# <script src="https://fastly.jsdelivr.net/npm/underscore@1.13.6/underscore-min.min.js" crossorigin="anonymous"></script>
# <script src="https://fastly.jsdelivr.net/npm/js-sequence-diagram@2.0.1/dist/sequence-diagram.min.js"crossorigin="anonymous"></script>
# """
    # gitalkJS = '<script src="https://fastly.jsdelivr.net/gh/zeromake/gitalk@1.8.1/docs/dist/gitalk.min.js" crossorigin="anonymous"></script>'
    # gitalkCSS = '<link rel="stylesheet" href="https://fastly.jsdelivr.net/gh/zeromake/gitalk@1.8.1/docs/dist/gitalk.css" crossorigin="anonymous">'
    # katexJS = '<script src="https://fastly.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js" crossorigin="anonymous"></script>'
    # katexCSS = '<link rel="stylesheet" href="https://fastly.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css" crossorigin="anonymous">'

    # cdnjs
#     jquery = '<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" crossorigin="anonymous"></script>'
#     slideout = '<script src="https://cdnjs.cloudflare.com/ajax/libs/slideout/1.0.1/slideout.min.js" crossorigin="anonymous"></script>'
#     fancyboxJS = '<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" crossorigin="anonymous"></script>'
#     fancyboxCSS = '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" crossorigin="anonymous">'
#     timeagoJS = '<script src="https://cdnjs.cloudflare.com/ajax/libs/timeago.js/4.0.2/timeago.min.js" crossorigin="anonymous"></script>'
#     timeagoLocalesJS = ''
#     flowchartDiagramsJS = """
# <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.3.0/raphael.min.js"crossorigin="anonymous"></script>
# <script src="https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.17.1/flowchart.min.js" crossorigin="anonymous"></script>"""
#     katexCSS = '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css" crossorigin="anonymous">'
#     katexJS= '<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js" crossorigin="anonymous"></script>'
    # staticfile
    jquery = '<script src="https://cdn.staticfile.org/jquery/3.7.1/jquery.min.js" crossorigin="anonymous"></script>'
    slideout = '<script src="https://cdn.staticfile.org/slideout/1.0.1/slideout.min.js" crossorigin="anonymous"></script>'
    fancyboxJS = '<script src="https://cdn.staticfile.org/fancybox/3.5.7/jquery.fancybox.min.js" crossorigin="anonymous"></script>'
    fancyboxCSS = '<link rel="stylesheet" href="https://cdn.staticfile.org/fancybox/3.5.7/jquery.fancybox.min.css" crossorigin="anonymous">'
    timeagoJS = '<script src="https://cdn.staticfile.org/timeago.js/4.0.2/timeago.min.js" crossorigin="anonymous"></script>'

    flowchartDiagramsJS = """
<script src="https://cdn.staticfile.org/raphael/2.3.0/raphael.min.js"crossorigin="anonymous"></script>
<script src="https://cdn.staticfile.org/flowchart/1.17.1/flowchart.min.js" crossorigin="anonymous"></script>"""
    sequenceDiagramsCSS = '<link rel="stylesheet" href="https://www.unpkg.com/js-sequence-diagram@2.0.1/dist/sequence-diagram-min.css" crossorigin="anonymous">'
    sequenceDiagramsJS = """
<script src="https://cdn.staticfile.org/webfont/1.6.28/webfontloader.js" crossorigin="anonymous"></script>
<script src="https://cdn.staticfile.org/snap.svg/0.5.1/snap.svg-min.js" crossorigin="anonymous"></script>
<script src="https://cdn.staticfile.org/underscore.js/1.13.6/underscore-min.min.js" crossorigin="anonymous"></script>
<script src="https://www.unpkg.com/js-sequence-diagram@2.0.1/dist/sequence-diagram-min.js"crossorigin="anonymous"></script>
"""
    katexJS = '<script src="https://cdn.staticfile.org/KaTeX/0.16.9/katex.min.js" crossorigin="anonymous"></script>'
    katexCSS = '<link rel="stylesheet" href="https://cdn.staticfile.org/KaTeX/0.16.9/katex.min.css" crossorigin="anonymous">'

    gitalkJS = '<script src="https://www.unpkg.com/@zeromake/gitalk@1.8.1/dist/gitalk.min.js" crossorigin="anonymous"></script>'
    gitalkCSS = '<link rel="stylesheet" href="https://www.unpkg.com/@zeromake/gitalk@1.8.1/dist/gitalk.css" crossorigin="anonymous">'



  # Display a message at the beginning of an article to warn the readers that it's content may be outdated.
  # 在文章开头显示提示信息，提醒读者文章内容可能过时。
  [params.outdatedInfoWarning]
    enable = true
    hint = 90               # Display hint if the last modified time is more than these days ago.    # 如果文章最后更新于这天数之前，显示提醒
    warn = 360              # Display warning if the last modified time is more than these days ago.    # 如果文章最后更新于这天数之前，显示警告

  [params.gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
    enable = false
    owner = ""              # Your GitHub ID
    repo = ""               # The repo to store comments
    clientId = ""           # Your client ID
    clientSecret = ""       # Your client secret

  [params.utterances]       # https://utteranc.es/
    enable = false
    owner = ""              # Your GitHub ID
    repo = ""               # The repo to store comments

  [params.gitalk]           # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
    enable = true
    owner = "zeromake"              # Your GitHub ID
    repo = "zeromake.github.io"               # The repo to store comments
    clientId = "6f4e103c0af2b0629e01"           # Your client ID
    clientSecret = "22f0c21510acbdda03c9067ee3aa2aee0c805c9f"       # Your client secret
#    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token"
#    proxy = "https://ray2.zeromake.com/login/oauth/access_token"
    proxy = "https://cors-server.huix.top/github_access_token"
    label = "gitment"

  # Valine.
  # You can get your appid and appkey from https://leancloud.cn
  # more info please open https://valine.js.org
  [params.valine]
    enable = false
    appId = '你的appId'
    appKey = '你的appKey'
    notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
    verify = false # Verification code
    avatar = 'mm'
    placeholder = '说点什么吧...'
    visitor = false

  [params.flowchartDiagrams]# see https://blog.olowolo.com/example-site/post/js-flowchart-diagrams/
    enable = true
    options = ""

  [params.sequenceDiagrams] # see https://blog.olowolo.com/example-site/post/js-sequence-diagrams/
    enable = true
    options = ""            # default: "{theme: 'simple'}"

  [params.busuanzi]         # count web traffic by busuanzi                             # 是否使用不蒜子统计站点访问量
    enable = false
    siteUV = true
    sitePV = true
    pagePV = true

  [params.reward]                                         # 文章打赏
    enable = true
    wechat = "/public/wechat-qr-code.png"           # 微信二维码
    alipay = "/public/alipay-qr-code.svg"           # 支付宝二维码

  [params.social]                                         # 社交链接
    a-email = "a390720046@gmail.com"
    # b-stack-overflow = "http://localhost:1313"
    # c-twitter = "http://localhost:1313"
    # d-facebook = "http://localhost:1313"
    # e-linkedin = "http://localhost:1313"
    # f-google = "http://localhost:1313"
    g-github = "https://github.com/zeromake"
    # h-weibo = "http://localhost:1313"
    # i-zhihu = "http://localhost:1313"
    # j-douban = "http://localhost:1313"
    # k-pocket = "http://localhost:1313"
    # l-tumblr = "http://localhost:1313"
    # m-instagram = "http://localhost:1313"
    # n-gitlab = "http://localhost:1313"
    # o-bilibili = "http://localhost:1313"

# See https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true      # 12.214.31.144 -> 12.214.31.0
  [privacy.youtube]
    privacyEnhanced = true

# see https://gohugo.io/getting-started/configuration-markup
[markup]
  [markup.tableOfContents]
    startLevel = 1
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      # 自定义 goldmark 插件，效果就是让 md 的一些语法转移到前端，这里就是把 tex 公式直接放置到 html 里
      [[markup.goldmark.extensions.raws]]
        IsBlock = true
        Tag = "div"
        Classname = "tex-block"
        PrefixMark = "$$"
        SuffixMark = "$$"
        Trigger = "$"
      [[markup.goldmark.extensions.raws]]
        Tag = "span"
        ClassName = "tex-inline"
        PrefixMark = "$"
        SuffixMark = "$"
        Trigger = "$"

# 将下面这段配置取消注释可以使 hugo 生成 .md 文件
# Uncomment these options to make hugo output .md files.
#[mediaTypes]
#  [mediaTypes."text/plain"]
#    suffixes = ["md"]
#
#[outputFormats.MarkDown]
#  mediaType = "text/plain"
#  isPlainText = true
#  isHTML = false
#
#[outputs]
#  home = ["HTML", "RSS"]
#  page = ["HTML", "MarkDown"]
#  section = ["HTML", "RSS"]
#  taxonomy = ["HTML", "RSS"]
#  taxonomyTerm = ["HTML"]
