baseURL = "https://blog.zeromake.com/"
languageCode = "zh-cn"
title = "zeromake'blog"
theme = "next"

BuildDrafts =  false
CanonifyUrls =  true
DefaultContentLanguage = "zh"
DisablePathToLower =  true
HasCJKLanguage = true
LanguageCode = "zh-CN"
PaginatePath =  "p"
Paginate = 8


[blackfriday]
    smartypants = false

[permalinks]
    post = "/pages/:slug/"
    page = "/:slug/"


[Params]
  Introduce = "简介"
  Description = "zeromake 的个人博客"
  Keywords =  "个人博客,Golang,高并发,笔记"
  Subtitle = "keep coding and thinking!"
  Imglogo = "/img/logo.ico"
  AuthorImg = "/img/zeromake.svg" # options: false
  DateFormat = "2006-01-02"
  YearFormat = "2006年"
  MonthFormat = "01-02"
  Fancybox = true

[Author]
  Name = "zeromake"

[Params.Share]
  Baidu = false

[[Menu.Main]]
  Name = "首页"
  Pre = "home"
  URL = "/"
  Weight = 1
[[Menu.Main]]
  Name = "关于"
  Pre = "user"
  URL = "/about/"
  Weight = 2
[[Menu.Main]]
  Name = "分类"
  Pre = "folder"
  URL = "/categories/"
  Weight = 3
[[Menu.Main]]
  Name = "标签"
  Pre = "tags"
  URL = "/tags/"
  Weight = 4
[[Menu.Main]]
  Name = "归档"
  Pre = "archive"
  URL = "/post/"
  Weight = 5
[[Menu.Main]]
  Name = "简历"
  Pre = "credit-card"
  URL = "/resume/"
  Weight = 5

[[Params.Socials]]
  Name = "GitHub"
  Icon = "github"
  URL = "https://github.com/zeromake"

# See [Color Schemes](https://xyproto.github.io/splash/docs/)
# See [inline html](https://github.com/flysnow-org/maupassant-hugo/issues/84)

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    lineNos = true
    style = "monokailight"
